version: '3.5'

services:
  hardhat-node:
    build: ./
    environment:
      ALCHEMY_KEY: ${ALCHEMY_KEY:?err}
      MAINNET_FORK: "true"
    ports:
      - 8545:8545
    healthcheck:
      test: "bash -c '</dev/tcp/localhost/8545' 2>/dev/null"
      interval: 10s
  augmented:
    build: ./
    environment:
      MAINNET_FORK: "true"
    command: bash -c "yarn hardhat augmented:mainnet --network docker && cp ui-config.json /opt/www/ui-config.json"
    volumes:
      - www:/opt/www
    depends_on:
      hardhat-node:
        condition: service_healthy
  www:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - www:/usr/share/nginx/html
volumes:
  www:
