version: '3.5'

services:
  hardhat-node:
    build: ./
    environment:
      ALCHEMY_KEY: ${ALCHEMY_KEY:?err}
      MAINNET_FORK: "true"
    ports:
      - 8545:8545
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    healthcheck:
      test: "bash -c '</dev/tcp/localhost/8545' 2>/dev/null"
      interval: 20s
  augmented:
    build: ./
    environment:
      MAINNET_FORK_BLOCK_NUMBER: "12991000"
      MAINNET_FORK: "true"
    command: bash -c "yarn hardhat augmented:mainnet --network docker && cp ui-config.json /opt/www/ui-config.json"
    volumes:
      - www:/opt/www
    depends_on:
      hardhat-node:
        condition: service_healthy
  www:
    image: nginx:stable
    ports:
      - 8080:80
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  explorer:
        image: alethio/ethereum-lite-explorer
        ports:
          - 8085:80
        environment:
          APP_NODE_URL: "http://${PUBLIC_IP:-localhost}:8545"
volumes:
  www:
