import { MainnetReserves, MainnetStableBaseRates } from './reservesConfigs_main';

const bscReserveDefault = MainnetReserves.WETH;
const bscStableDefault = MainnetStableBaseRates.WETH;

export const BscStableBaseRates = {
  DAI:  MainnetStableBaseRates.DAI,
  USDC: MainnetStableBaseRates.USDC,
  USDT: MainnetStableBaseRates.USDT,
  WBNB: MainnetStableBaseRates.WETH,

  BTCB: bscStableDefault,
  BCH: bscStableDefault,
  ETH: bscStableDefault,
  BETH: bscStableDefault,
  BUSD: bscStableDefault,
  TUSD: bscStableDefault,
  DOT: bscStableDefault,
  SXP: bscStableDefault,
  XRP: bscStableDefault,
  ADA: bscStableDefault,
  TRX: bscStableDefault,
  LINK: bscStableDefault,
  LTC: bscStableDefault,
  DOGE: bscStableDefault,
  MATIC: bscStableDefault,
  FIL: bscStableDefault,
  INJ: bscStableDefault,
  CHR: bscStableDefault,
  REEF: bscStableDefault,
  TWT: bscStableDefault,
  LINA: bscStableDefault,
  CAKE: bscStableDefault,
  XVS: bscStableDefault,
  ALPACA: bscStableDefault,
  UNI: bscStableDefault,
  SUSHI: bscStableDefault,
  AAVE: bscStableDefault,
  BIFI: bscStableDefault,
  AUTO: bscStableDefault,
  DODO: bscStableDefault,
  ALPHA: bscStableDefault,
}

export const BscReserves = {
  DAI:  MainnetReserves.DAI,
  USDC: MainnetReserves.USDC,
  USDT: MainnetReserves.USDT,
  WBNB: MainnetReserves.WETH,

  BTCB: bscReserveDefault,
  BCH: bscReserveDefault,
  ETH: bscReserveDefault,
  BETH: bscReserveDefault,
  BUSD: bscReserveDefault,
  TUSD: bscReserveDefault,
  DOT: bscReserveDefault,
  SXP: bscReserveDefault,
  XRP: bscReserveDefault,
  ADA: bscReserveDefault,
  TRX: bscReserveDefault,
  LINK: bscReserveDefault,
  LTC: bscReserveDefault,
  DOGE: bscReserveDefault,
  MATIC: bscReserveDefault,
  FIL: bscReserveDefault,
  INJ: bscReserveDefault,
  CHR: bscReserveDefault,
  REEF: bscReserveDefault,
  TWT: bscReserveDefault,
  LINA: bscReserveDefault,
  CAKE: bscReserveDefault,
  XVS: bscReserveDefault,
  ALPACA: bscReserveDefault,
  UNI: bscReserveDefault,
  SUSHI: bscReserveDefault,
  AAVE: bscReserveDefault,
  BIFI: bscReserveDefault,
  AUTO: bscReserveDefault,
  DODO: bscReserveDefault,
  ALPHA: bscReserveDefault,  
}
